# Generated by Django 5.2 on 2025-05-08 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wrestler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_reigns', models.IntegerField(default=0)),
                ('total_days_as_champion', models.IntegerField(default=0)),
                ('longest_single_reign', models.IntegerField(default=0)),
                ('shortest_single_reign', models.IntegerField(default=0)),
                ('most_recent_reign', models.DateField(blank=True, null=True)),
                ('first_reign', models.DateField(blank=True, null=True)),
                ('most_recent_reign_end', models.DateField(blank=True, null=True)),
                ('days_since_last_reign', models.IntegerField(default=0)),
                ('title_diversity', models.IntegerField(default=0)),
                ('avg_gap_between_reigns', models.FloatField(default=0.0)),
                ('career_span_days', models.IntegerField(default=0)),
                ('avg_reigns_per_title', models.FloatField(default=0.0)),
                ('belts', models.ManyToManyField(related_name='wrestlers', to='predictor.belt')),
            ],
        ),
        migrations.CreateModel(
            name='Reign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('length', models.IntegerField()),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.belt')),
                ('wrestler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reigns', to='predictor.wrestler')),
            ],
        ),
    ]
