# Generated by Django 5.2 on 2025-05-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_belt_wrestler_reign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrestler',
            name='belts',
        ),
        migrations.AddField(
            model_name='wrestler',
            name='belt',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='avg_gap_between_reigns',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='avg_reigns_per_title',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='career_span_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='days_since_last_reign',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='longest_single_reign',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='shortest_single_reign',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='title_diversity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='total_days_as_champion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='total_reigns',
            field=models.IntegerField(),
        ),
    ]
