# Generated by Django 5.2 on 2025-05-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_remove_wrestler_belts_wrestler_belt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='average_reign_duration',
            field=models.FloatField(default=0.0),
        ),
    ]
